# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: balance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\x12\nbalance.v1\"!\n\x0bPingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2K\n\x0e\x42\x61lanceService\x12\x39\n\x04Ping\x12\x17.balance.v1.PingRequest\x1a\x18.balance.v1.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=29
  _globals['_PINGREQUEST']._serialized_end=62
  _globals['_PINGRESPONSE']._serialized_start=64
  _globals['_PINGRESPONSE']._serialized_end=94
  _globals['_BALANCESERVICE']._serialized_start=96
  _globals['_BALANCESERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
