# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from balance_service.interfaces.grpc import balance_pb2 as balance__service_dot_interfaces_dot_grpc_dot_balance__pb2

class BalanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/balance.v1.BalanceService/Ping',
                request_serializer=balance__service_dot_interfaces_dot_grpc_dot_balance__pb2.PingRequest.SerializeToString,
                response_deserializer=balance__service_dot_interfaces_dot_grpc_dot_balance__pb2.PingResponse.FromString)


class BalanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BalanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=balance__service_dot_interfaces_dot_grpc_dot_balance__pb2.PingRequest.FromString,
                    response_serializer=balance__service_dot_interfaces_dot_grpc_dot_balance__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'balance.v1.BalanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
