services:
  api-gateway:
    build:
      context: ./services/api-gateway
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./services/worker
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  balance-service:
    build:
      context: ./services/balance-service
    ports:
      - "50051:50051"

    # Optional: load shared config (kept consistent across services)
    env_file:
      - .env
