services:
  localstack:
    image: localstack/localstack:3.8
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "bash", "-lc", "awslocal sqs list-queues >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api-gateway:
    build:
      context: ./services/api-gateway
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/fintech-local-events
    ports:
      - "8000:8000"
    depends_on:
      localstack:
        condition: service_healthy

  worker:
    build:
      context: ./services/worker
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/fintech-local-events
    depends_on:
      localstack:
        condition: service_healthy

  balance-service:
    build:
      context: ./services/balance-service
    ports:
      - "50051:50051"

version: "3.9"
