# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: balance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\x12\nbalance.v1\"\r\n\x0bPingRequest\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x0eMetricsRequest\x12\x14\n\x0cprovider_ids\x18\x01 \x03(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\">\n\x0fMetricsResponse\x12+\n\x07metrics\x18\x01 \x03(\x0b\x32\x1a.balance.v1.ProviderMetric\"\xab\x01\n\x0eProviderMetric\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x15\n\rprovider_name\x18\x02 \x01(\t\x12\x15\n\rprovider_type\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x17\n\x0f\x61vailable_cents\x18\x05 \x01(\x03\x12\x14\n\x0cledger_cents\x18\x06 \x01(\x03\x12\x15\n\ras_of_unix_ms\x18\x07 \x01(\x03\x32\x92\x01\n\x0e\x42\x61lanceService\x12\x39\n\x04Ping\x12\x17.balance.v1.PingRequest\x1a\x18.balance.v1.PingResponse\x12\x45\n\nGetMetrics\x12\x1a.balance.v1.MetricsRequest\x1a\x1b.balance.v1.MetricsResponseBOZMgithub.com/christk1/fintech-platform/services/balance-service/proto;balancev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/christk1/fintech-platform/services/balance-service/proto;balancev1'
  _globals['_PINGREQUEST']._serialized_start=29
  _globals['_PINGREQUEST']._serialized_end=42
  _globals['_PINGRESPONSE']._serialized_start=44
  _globals['_PINGRESPONSE']._serialized_end=74
  _globals['_METRICSREQUEST']._serialized_start=76
  _globals['_METRICSREQUEST']._serialized_end=133
  _globals['_METRICSRESPONSE']._serialized_start=135
  _globals['_METRICSRESPONSE']._serialized_end=197
  _globals['_PROVIDERMETRIC']._serialized_start=200
  _globals['_PROVIDERMETRIC']._serialized_end=371
  _globals['_BALANCESERVICE']._serialized_start=374
  _globals['_BALANCESERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
